name: Test

on:
  - push
  - pull_request

jobs:
  type_test:
    name: Type Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: 1.26.2

      - run: deno cache --unstable **/*.ts

  code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: KSXGitHub/github-actions-sane-fmt@0.2.22
